# Helper script to install/verify wolf commands in PowerShell profile
# Run this script if wolf commands are not available after installation

param(
    [switch]$Check,
    [switch]$Install,
    [switch]$ShowPath
)

# Get the installation directory (assume we're in the install directory)
$installDir = Get-Location
$venvScripts = Join-Path $installDir ".venv\Scripts"

# Get PowerShell profile path
$profilePath = $PROFILE

if ($ShowPath) {
    Write-Host "PowerShell Profile Path: $profilePath" -ForegroundColor Cyan
    Write-Host "Installation Directory: $installDir" -ForegroundColor Cyan
    Write-Host "Venv Scripts: $venvScripts" -ForegroundColor Cyan
    exit 0
}

if ($Check) {
    Write-Host "Checking wolf command installation..." -ForegroundColor Cyan
    Write-Host ""
    
    # Check if profile exists
    if (Test-Path $profilePath) {
        $profileContent = Get-Content $profilePath -Raw
        if ($profileContent -match "# Wolf CLI Commands") {
            Write-Host "✓ Wolf commands found in profile" -ForegroundColor Green
            Write-Host "  Profile: $profilePath" -ForegroundColor Gray
        } else {
            Write-Host "✗ Wolf commands NOT found in profile" -ForegroundColor Red
            Write-Host "  Profile: $profilePath" -ForegroundColor Gray
        }
    } else {
        Write-Host "✗ PowerShell profile does not exist" -ForegroundColor Red
        Write-Host "  Profile: $profilePath" -ForegroundColor Gray
    }
    
    # Check if console scripts exist
    Write-Host ""
    Write-Host "Checking console scripts..." -ForegroundColor Cyan
    $scripts = @('wolf.exe', 'wolfv.exe', 'wolfcamera.exe', 'wolfw.exe', 'wolfem.exe')
    foreach ($script in $scripts) {
        $scriptPath = Join-Path $venvScripts $script
        if (Test-Path $scriptPath) {
            Write-Host "  ✓ $script" -ForegroundColor Green
        } else {
            Write-Host "  ✗ $script (not found)" -ForegroundColor Red
        }
    }
    
    # Check if functions are loaded
    Write-Host ""
    Write-Host "Checking if functions are loaded in current session..." -ForegroundColor Cyan
    $functions = @('wolf', 'wolfv', 'wolfcamera', 'wolfw', 'wolfem')
    foreach ($func in $functions) {
        if (Get-Command $func -ErrorAction SilentlyContinue) {
            Write-Host "  ✓ $func (loaded)" -ForegroundColor Green
        } else {
            Write-Host "  ✗ $func (not loaded - run: . `$PROFILE)" -ForegroundColor Yellow
        }
    }
    
    exit 0
}

if ($Install) {
    Write-Host "Installing wolf commands to PowerShell profile..." -ForegroundColor Cyan
    Write-Host ""
    
    # Ensure profile directory exists
    $profileDir = Split-Path $profilePath -Parent
    if (-not (Test-Path $profileDir)) {
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
        Write-Host "Created profile directory: $profileDir" -ForegroundColor Green
    }
    
    # Check if already installed
    if (Test-Path $profilePath) {
        $profileContent = Get-Content $profilePath -Raw
        if ($profileContent -match "# Wolf CLI Commands") {
            Write-Host "Wolf commands already installed in profile (skipping)" -ForegroundColor Yellow
            Write-Host "To reload, run: . `$PROFILE" -ForegroundColor Cyan
            exit 0
        }
    }
    
    # Check if console scripts exist
    $wolfExe = Join-Path $venvScripts "wolf.exe"
    if (-not (Test-Path $wolfExe)) {
        Write-Host "Error: Console scripts not found at: $venvScripts" -ForegroundColor Red
        Write-Host "Please run the installer first or ensure setup.py install completed successfully." -ForegroundColor Red
        exit 1
    }
    
    # Generate functions
    $functions = @"
# Wolf CLI Commands - Auto-generated by install_wolf_profile.ps1
# Wolf CLI command functions
function wolf {
    param([string[]]`$args)
    & "$(Join-Path $venvScripts 'wolf.exe')" `$args
}

function wolfv {
    param([string[]]`$args)
    & "$(Join-Path $venvScripts 'wolfv.exe')" `$args
}

function wolfcamera {
    param([string[]]`$args)
    & "$(Join-Path $venvScripts 'wolfcamera.exe')" `$args
}

function wolfw {
    param([string[]]`$args)
    & "$(Join-Path $venvScripts 'wolfw.exe')" `$args
}

function wolfem {
    param([string[]]`$args)
    & "$(Join-Path $venvScripts 'wolfem.exe')" `$args
}
# End Wolf CLI Commands
"@
    
    # Append to profile
    try {
        Add-Content -Path $profilePath -Value $functions -Encoding UTF8
        Write-Host "✓ Added wolf commands to PowerShell profile" -ForegroundColor Green
        Write-Host "  Profile: $profilePath" -ForegroundColor Gray
        Write-Host ""
        Write-Host "To load the commands in this session, run:" -ForegroundColor Cyan
        Write-Host "  . `$PROFILE" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "Or restart PowerShell." -ForegroundColor Cyan
    } catch {
        Write-Host "Error: Could not write to profile: $_" -ForegroundColor Red
        exit 1
    }
    
    exit 0
}

# Default: show usage
Write-Host "Wolf CLI Profile Installation Helper" -ForegroundColor Cyan
Write-Host ""
Write-Host "Usage:" -ForegroundColor Yellow
Write-Host "  .\install_wolf_profile.ps1 -Check      # Check installation status"
Write-Host "  .\install_wolf_profile.ps1 -Install     # Install commands to profile"
Write-Host "  .\install_wolf_profile.ps1 -ShowPath   # Show profile and install paths"
Write-Host ""
Write-Host "Quick fix if commands not working:" -ForegroundColor Cyan
Write-Host "  1. Run: .\install_wolf_profile.ps1 -Check"
Write-Host "  2. If not installed, run: .\install_wolf_profile.ps1 -Install"
Write-Host "  3. Then run: . `$PROFILE"

